src/Entity/Animaux.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnimauxRepository")
 */
class Animaux
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $audio;

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAudio(): ?string
    {
        return $this->audio;
    }

    public function setAudio(string $audio): self
    {
        $this->audio = $audio;

        return $this;
    }
}

templates/_mail.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
</head>
<body>
    <p>{% if prenom != '' %} {{ prenom }} {% endif %}
        vous a envoyé un message.
    </p>
    <p>{{ message }}</p>
</body>
</html>

templates/birds.html.twig
{% extends 'base/baseFamily.html.twig' %}

{% block main %}
    <main>
        <div class="contentFamily">
            <div class="titleBirds">
                <img src="{{ asset('assets/img/main/titleBirds.png') }}" alt="">
            </div>
            <!--------------------------IMAGE BUGS--------------------------------->
            <div class="sideFamily1">
                <a href="{{ path('bugs_page') }}"><img src="{{ asset('assets/img/animals/bugs.png') }}" alt=""></a>
            </div>

            <!--------------------------IMAGE BIRDS--------------------------------->
            <div class="birdsFamily">
                <img src="{{ asset('assets/img/animals/birds.png') }}" alt="">
                <div class="pheasant">
                    <a href="{{ path('animals', {'id': 13}) }}"><img src="{{ asset('assets/img/animals/pheasantHitbox.png') }}" alt="" onmouseover="PlaySound('pheasantSound')" onmouseout="StopSound('pheasantSound')">
                        <div class="animalText">Je suis le faisan !</div>
                    </a>
                </div>
                <div class="toucan">
                    <a href="{{ path('animals', {'id': 14}) }}"><img src="{{ asset('assets/img/animals/toucanHitbox.png') }}" alt="" onmouseover="PlaySound('toucanSound')" onmouseout="StopSound('toucanSound')">
                        <div class="animalText">Je suis le toucan !</div>
                    </a>
                </div>
                <div class="peacock">
                    <a href="{{ path('animals', {'id': 15}) }}"><img src="{{ asset('assets/img/animals/peacockHitbox.png') }}" alt="" onmouseover="PlaySound('peacockSound')" onmouseout="StopSound('peacockSound')">
                        <div class="animalText">Je suis le paon !</div>
                    </a>
                </div>
                <div class="parrot">
                    <a href="{{ path('animals', {'id': 16}) }}"><img src="{{ asset('assets/img/animals/parrotHitbox.png') }}" alt="" onmouseover="PlaySound('parrotSound')" onmouseout="StopSound('parrotSound')">
                        <div class="animalText">Je suis le perroquet !</div>
                    </a>
                </div>
                <div class="penguin">
                    <a href="{{ path('animals', {'id': 17}) }}"><img src="{{ asset('assets/img/animals/penguinHitbox.png') }}" alt="" onmouseover="PlaySound('penguinSound')" onmouseout="StopSound('penguinSound')">
                        <div class="animalText">Je suis le manchot !</div>
                    </a>
                </div>
                <div class="parakeet">
                    <a href="{{ path('animals', {'id': 18}) }}"><img src="{{ asset('assets/img/animals/parakeetHitbox.png') }}" alt="" onmouseover="PlaySound('parakeetSound')" onmouseout="StopSound('parakeetSound')">
                        <div class="animalText">Je suis la perruche !</div>
                    </a>
                </div>
            </div>

            <!--------------------------IMAGE FARM--------------------------------->
            <div class="sideFamily2">
                <a href="{{ path('farm_page') }}"><img src="{{ asset('assets/img/animals/farm.png') }}" alt=""></a>
            </div>
        </div>

        <!--------------------------MESSAGES POP-UP--------------------------------->
        <div class="popUpFamily">
            <span id="family">Choisis un animal et écoute ce qu'il a à te raconter !</span>
        </div>
        <script>
            $( document ).ready(function() {
                $('.popUpFamily').slideUp().delay(1000).slideDown();
                $('.popUpFamily').slideDown().delay(5000).slideUp()
            });
        </script>

        <div class="popUpFamilyAnnexes1">
            <span id="familyAnnexes">Tu peux voir les autres familles en cliquant ici !</span>
        </div>
        <script>
            $( document ).ready(function() {
                $('.popUpFamilyAnnexes1').slideUp().delay(7000).slideDown();
                $('.popUpFamilyAnnexes1').slideDown().delay(5000).slideUp()
            });
        </script>

        <div class="popUpFamilyAnnexes2">
            <span id="familyAnnexes2">Et ici !</span>
        </div>
        <script>
            $( document ).ready(function() {
                $('.popUpFamilyAnnexes2').slideUp().delay(13000).slideDown();
                $('.popUpFamilyAnnexes2').slideDown().delay(5000).slideUp()
            });
        </script>

        <!-----------------------------SONS POP-UP--------------------------------->
        <audio id='pheasantSound' src="{{ asset('assets/song/pheasant.mp3') }}"/>
        <audio id='toucanSound' src="{{ asset('assets/song/toucan.mp3') }}"/>
        <audio id='peacockSound' src="{{ asset('assets/song/peacock.mp3') }}"/>
        <audio id='parrotSound' src="{{ asset('assets/song/parrot.mp3') }}"/>
        <audio id='penguinSound' src="{{ asset('assets/song/penguin.mp3') }}"/>
        <audio id='parakeetSound' src="{{ asset('assets/song/parakeet.mp3') }}"/>

    </main>
{% endblock %}

templates/bugs.html.twig
{% extends 'base/baseFamily.html.twig' %}

{% block main %}
    <main>
        <div class="contentFamily">
            <div class="titleBugs">
                <img src="{{ asset('assets/img/main/titleBugs.png') }}" alt="">
            </div>

            <!--------------------------IMAGE FARM--------------------------------->
            <div class="sideFamily1">
                <a href="{{ path('farm_page') }}"><img src="{{ asset('assets/img/animals/farm.png') }}" alt=""></a>
            </div>

            <!--------------------------IMAGE BUGS--------------------------------->
            <div class="bugsFamily">
                <img src="{{ asset('assets/img/animals/bugs.png') }}" alt="">
                <div class="ladyBird">
                    <a href="{{ path('animals', {'id': 7}) }}"><img src="{{ asset('assets/img/animals/ladyBirdHitbox.png') }}" alt="" onmouseover="PlaySound('dogSound')" onmouseout="StopSound('dogSound')">
                        <div class="animalText">Je suis la coccinelle !</div>
                    </a>
                </div>
                <div class="snail">
                    <a href="{{ path('animals', {'id': 8}) }}"><img src="{{ asset('assets/img/animals/snailHitbox.png') }}" alt="" onmouseover="PlaySound('dogSound')" onmouseout="StopSound('dogSound')">
                        <div class="animalText">Je suis l'escargot !</div>
                    </a>
                </div>
                <div class="grasshopper">
                    <a href="{{ path('animals', {'id': 9}) }}"><img src="{{ asset('assets/img/animals/grasshopperHitbox.png') }}" alt="" onmouseover="PlaySound('dogSound')" onmouseout="StopSound('dogSound')">
                        <div class="animalText">Je suis la sauterelle !</div>
                    </a>
                </div>
                <div class="caterpillar">
                    <a href="{{ path('animals', {'id': 10}) }}"><img src="{{ asset('assets/img/animals/caterpillarHitbox.png') }}" alt="" onmouseover="PlaySound('dogSound')" onmouseout="StopSound('dogSound')">
                        <div class="animalText">Je suis la chenille !</div>
                    </a>
                </div>
                <div class="spider">
                    <a href="{{ path('animals', {'id': 11}) }}"><img src="{{ asset('assets/img/animals/spiderHitbox.png') }}" alt="" onmouseover="PlaySound('dogSound')" onmouseout="StopSound('dogSound')">
                        <div class="animalText">Je suis l'araignée' !</div>
                    </a>
                </div>
                <div class="dragonfly">
                    <a href="{{ path('animals', {'id': 12}) }}"><img src="{{ asset('assets/img/animals/dragonflyHitbox.png') }}" alt="" onmouseover="PlaySound('dogSound')" onmouseout="StopSound('dogSound')">
                        <div class="animalText">Je suis la libellule !</div>
                    </a>
                </div>
            </div>

            <!--------------------------IMAGE BIRDS--------------------------------->
            <div class="sideFamily2">
                <a href="{{ path('birds_page') }}"><img src="{{ asset('assets/img/animals/birds.png') }}" alt=""></a>
            </div>
        </div>

        <!--------------------------MESSAGES POP-UP--------------------------------->
        <div class="popUpFamily">
            <span id="family">Choisis un animal et écoute ce qu'il a à te raconter !</span>
        </div>
        <script>
            $( document ).ready(function() {
                $('.popUpFamily').slideUp().delay(1000).slideDown();
                $('.popUpFamily').slideDown().delay(5000).slideUp()
            });
        </script>

        <div class="popUpFamilyAnnexes1">
            <span id="familyAnnexes">Tu peux voir les autres familles en cliquant ici !</span>
        </div>
        <script>
            $( document ).ready(function() {
                $('.popUpFamilyAnnexes1').slideUp().delay(7000).slideDown();
                $('.popUpFamilyAnnexes1').slideDown().delay(5000).slideUp()
            });
        </script>

        <div class="popUpFamilyAnnexes2">
            <span id="familyAnnexes2">Et ici !</span>
        </div>
        <script>
            $( document ).ready(function() {
                $('.popUpFamilyAnnexes2').slideUp().delay(13000).slideDown();
                $('.popUpFamilyAnnexes2').slideDown().delay(5000).slideUp()
            });
        </script>

        <!-----------------------------SONS POP-UP--------------------------------->
{#
        <audio id='ladyBirdSound' src="{{ asset('assets/song/ladyBird.mp3') }}"/>
#}

    </main>
{% endblock %}

templates/contact.html.twig
{% extends 'base/baseQuiz.html.twig' %}

{% block main %}

    <div class="formLogin">
        <a href="{{ path('home_lesZanimeo') }}"><img class="homeButton" src="{{ asset('assets/img/main/home.jpg') }}" alt="Bouton de retour à l'accueil"></a>
        <h1>Contact</h1>

        <!--------------------------FORMULAIRE CONTACT--------------------------------->
        {{ form_start(contactForm, {'attr': {'novalidate': 'novalidate'}}) }}

        <div class="formLogin2">
            <div class="formLogin3">
                <div class="form-group">
                    {{ form_label(contactForm.prenom, 'Prénom', {'label_attr':{'class':'labelContact'}}) }}
                    {{ form_widget(contactForm.prenom, {'attr': {'class': 'form-control', 'placeholder': 'Quel est ton prénnom ?' }}) }}
                </div>
                <div class="form-group">
                    {{ form_label(contactForm.email, 'Email', {'label_attr':{'class':'labelContact'}}) }}
                    {{ form_widget(contactForm.email, {'attr': {'class': 'form-control', 'placeholder': 'Quel est ton email ?' }}) }}
                </div>
                <div class="form-group">
                    {{ form_label(contactForm.message, 'Message', {'label_attr':{'class':'labelContact'}}) }}
                    {{ form_widget(contactForm.message, {'attr': {'class': 'form-control', 'placeholder': 'Quel est ton message ?' }}) }}
                </div>
                <div class="form-group">
                    {{ form_label(contactForm.envoyer) }}
                    {{ form_widget(contactForm.envoyer , {'attr': {'class': 'btn btn-light'}}) }}
                </div>

                <!--------------------------MESSAGE DE CONFIRMATION D'ENREGISTREMENT--------------------------------->
                <div class="messageConfirmation">
                    {% for messages in app.flashes %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endfor %}
                </div>
            </div>

            {{ form_end(contactForm) }}

        </div>
    </div>

{% endblock %}

templates/farm.html.twig
{% extends 'base/baseFamily.html.twig' %}

{% block main %}
    <main>
        <div class="contentFamily">
            <div class="titleFarm">
                <img src="{{ asset('assets/img/main/titleFarm.png') }}" alt="">
            </div>

            <!--------------------------IMAGE BIRDS--------------------------------->
            <div class="sideFamily1">
                <a href="{{ path('birds_page') }}"><img src="{{ asset('assets/img/animals/birds.png') }}" alt="Raccourcis pour accéder aux oiseaux"></a>
            </div>

            <!--------------------------IMAGE FARM--------------------------------->
            <div class="farmFamily">
                <img src="{{ asset('assets/img/animals/farm.png') }}" alt="">
                <div class="dog">
                    <a href="{{ path('animals', {'id': 1}) }}"><img src="{{ asset('assets/img/animals/dogHitbox.png') }}" alt="Image du chien" onmouseover="PlaySound('dogSound')" onmouseout="StopSound('dogSound')">
                        <div class="animalText">Je suis le Chien !</div>
                    </a>
                </div>
                <div class="horse">
                    <a href="{{ path('animals', {'id': 2}) }}"><img src="{{ asset('assets/img/animals/horseHitbox.png') }}" alt="Image du cheval" onmouseover="PlaySound('horseSound')" onmouseout="StopSound('horseSound')">
                        <div class="animalText">Je suis le Cheval !</div>
                    </a>
                </div>
                <div class="pig">
                    <a href="{{ path('animals', {'id': 3}) }}"><img src="{{ asset('assets/img/animals/pigHitbox.png') }}" alt="Image du cochon" onmouseover="PlaySound('pigSound')" onmouseout="StopSound('pigSound')">
                        <div class="animalText">Je suis le Cochon !</div>
                    </a>
                </div>
                <div class="rabbit">
                    <a href="{{ path('animals', {'id': 4}) }}"><img src="{{ asset('assets/img/animals/rabbitHitbox.png') }}" alt="Image du lapin" onmouseover="PlaySound('rabbitSound')" onmouseout="StopSound('rabbitSound')">
                        <div class="animalText">Je suis le Lapin !</div>
                    </a>
                </div>
                <div class="sheep">
                    <a href="{{ path('animals', {'id': 5}) }}"><img src="{{ asset('assets/img/animals/sheepHitbox.png') }}" alt="Image du mouton" onmouseover="PlaySound('sheepSound')" onmouseout="StopSound('sheepSound')">
                        <div class="animalText">Je suis le Mouton !</div>
                    </a>
                </div>
                <div class="cow">
                    <a href="{{ path('animals', {'id': 6}) }}"><img src="{{ asset('assets/img/animals/cowHitbox.png') }}" alt="Image de la vache" onmouseover="PlaySound('cowSound')" onmouseout="StopSound('cowSound')">
                        <div class="animalText">Je suis la vache !</div>
                    </a>
                </div>
            </div>

            <!--------------------------IMAGE BUGS--------------------------------->
            <div class="sideFamily2">
                <a href="{{ path('bugs_page') }}"><img src="{{ asset('assets/img/animals/bugs.png') }}" alt="Raccourcis pour les insectes"></a>
            </div>
        </div>

        <!--------------------------MESSAGES POP-UP--------------------------------->
        <div class="popUpFamily">
            <span id="family">Choisis un animal et écoute ce qu'il a à te raconter !</span>
        </div>

        <div class="popUpFamilyAnnexes1">
            <span id="familyAnnexes">Tu peux voir les autres familles en cliquant ici !</span>
        </div>
        <script>
            $( document ).ready(function() {
                $('.popUpFamily').slideUp().delay(1000).slideDown();
                $('.popUpFamily').slideDown().delay(5000).slideUp();
            });
        </script>
        <script>
            $( document ).ready(function() {
                $('.popUpFamilyAnnexes1').slideUp().delay(7000).slideDown();
                $('.popUpFamilyAnnexes1').slideDown().delay(5000).slideUp()
            });
        </script>
        <div class="popUpFamilyAnnexes2">
            <span id="familyAnnexes2">Et ici !</span>
        </div>
        <script>
            $( document ).ready(function() {
                $('.popUpFamilyAnnexes2').slideUp().delay(12500).slideDown();
                $('.popUpFamilyAnnexes2').slideDown().delay(5000).slideUp()
            });
        </script>
        <!-----------------------------SONS POP-UP--------------------------------->
        <audio id='dogSound' src="{{ asset('assets/song/dog.mp3') }}"/>
        <audio id='horseSound' src="{{ asset('assets/song/horse.mp3') }}"/>
        <audio id='pigSound' src="{{ asset('assets/song/pig.mp3') }}"/>
{#
        <audio id='rabbitSound' src="{{ asset('assets/song/rabbit.mp3') }}"/>
#}
        <audio id='sheepSound' src="{{ asset('assets/song/sheep.mp3') }}"/>
        <audio id='cowSound' src="{{ asset('assets/song/cow.mp3') }}"/>

    </main>
{% endblock %}

templates/home.html.twig
{% extends 'base/base.html.twig' %}

{% block main %}

<main>
    <a href="{{ path('quiz') }}"><img class="quiz" src="{{ asset('assets/img/main/quiz1.png') }}" alt="Ceci est un bouton pour accéder au Quiz" tabindex="2" onmouseover="PlaySound('quizSound')"
         onmouseout="StopSound('quizSound')"></a>

    <!--------------------------NAVBAR--------------------->
    <nav class="sidenav" role="navigation" aria-label="Menu principal">
        {% if is_granted("ROLE_ADMIN") %}
            {{ 'layout.logged_in_as'|trans({'%username%': app.user.username}, 'FOSUserBundle') }} |
            <a href="{{ path('admin') }}">Espace Admin</a> |
            <a href="{{ path('fos_user_security_logout') }}">Se déconnecter</a> |
            <a href="{{ path('contact') }}">Contact</a>
        {%  elseif is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            {{ 'layout.logged_in_as'|trans({'%username%': app.user.username}, 'FOSUserBundle') }} |
            <a href="{{ path('fos_user_security_logout') }}">Se déconnecter</a> |
            <a href="{{ path('contact') }}">Contact</a>

        {% else %}
            <a href="{{ path('admin') }}">Se connecter</a> |
            <a href="{{ path('fos_user_registration_register') }}">S'inscrire</a> |
            <a href="{{ path('contact') }}">Contact</a>
        {% endif %}
    </nav>

    <!--------------------------TITRE LOGO--------------------->
    <div>
        <div class="title">
            <img src="{{ asset('assets/img/main/title.png') }}" alt="">
        </div>
    </div>

    <!---------------------------ICONE MEGAPHONE------------------------------->
    <div class="circleMegaphone">
    </div>
    <div class="button play">
        <img src="{{ asset('assets/img/main/megaphone.svg') }}" id="player" alt="">
    </div>

    <!---------------------------BACKGROUND AUDIO (SON NATURE)------------------------------->
    <audio id="background_audio" autoplay="autoplay">
        <source src="{{ asset('assets/song/nature.mp3') }}" />
    </audio>

    <!--------------------------3 IMAGES FAMILLES ANIMAUX--------------------------------->
    <div class="content">
        <a href="{{ path('farm_page') }}" class="farmHome"><img src="{{ asset('assets/img/animals/farm.png') }}" alt="Accéder aux animaux de la ferme" onmouseover="PlaySound('farmSound')" onmouseout="StopSound('farmSound')"></a>
        <a href="{{ path('bugs_page') }}" class="bugsHome"><img src="{{ asset('assets/img/animals/bugs.png') }}" alt="Accéder aux insectes" onmouseover="PlaySound('bugsSound')" onmouseout="StopSound('bugsSound')"></a>
        <a href="{{ path('birds_page') }}" class="birdsHome"><img src="{{ asset('assets/img/animals/birds.png') }}" alt="Accéder aux oiseaux" onmouseover="PlaySound('birdsSound')" onmouseout="StopSound('birdsSound')"></a>

        <!--------------------------MESSAGES POP-UP--------------------------------->
        <div class="popUpMegaphone">
            <span id="m">Tu peux désactiver le son en cliquant sur l'icône !</span>
        </div>
        <div class="popUpHome">
            <span id="a">Choisis ta famille d'animaux et écoute ce qu'ils ont à te raconter !</span>
        </div>
        <div class="popUpQuiz">
            <span id="q">Clique ici pour jouer au Quiz et tester tes connaissances !</span>
        </div>
        <div class="popUpRegistration">
            <span id="r">Mais avant de jouer, nous t'invitons à t'inscrire sur le site !</span>
        </div>

        <!-----------------------------SONS POP-UP--------------------------------->
        <audio id='quizSound' src="{{ asset('assets/song/quiz.mp3') }}"/>
        <audio id='farmSound' src="{{ asset('assets/song/farm.mp3') }}"/>
        <audio id='bugsSound' src="{{ asset('assets/song/bugs.mp3') }}"/>
        <audio id='birdsSound' src="{{ asset('assets/song/birds.mp3') }}"/>

    </div>
</main>

{% endblock %}

templates/questions.html.twig
{% extends 'base/baseQuiz.html.twig' %}

{% block main %}
    <main>
        <div class="contentQuiz">
            <div class="quizHeader">
                <div class="homeButtonQuiz">
                    <a href="{{ path('home_lesZanimeo') }}"><img src="{{ asset('assets/img/main/home2.jpg') }}" alt=""></a>
                </div>
                <h1 class="questionNumber">{{ questions.libelle }}</h1>
            </div>
            <div class="contentQuestionsQuiz">

                <!---------------------------IMAGE ANIMAL------------------------------->
                <div class="contentImgQuiz">
                    <img src="{{ asset('assets/img/animals') }}/{{ questions.image }}" alt="">
                </div>

                <!---------------------------CONTENU QUESTIONS------------------------------->
                <div class="contentRightQuiz">
                    <h1 class="questionMessage">VRAI OU FAUX ?</h1><br><br>
                    <p>{{ questions.resume }}<br><br><br>
                     <div class="btn-group" role="group" aria-label="Button">
                        <a href="{{ path('responses', {'id': questions.responses.first.id, 'goodResponses': goodResponses}) }}">
                            <button type="button" class="btn btn-info">VRAI</button></a>&nbsp;&nbsp;
                    </div>
                    <div class="btn-group" role="group" aria-label="Button">
                        <a href="{{ path('responses', {'id': questions.responses.last.id, 'goodResponses': goodResponses}) }}">
                            <button type="button" class="btn btn-info">FAUX</button></a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/quiz.html.twig
{% extends 'base/baseQuiz.html.twig' %}

{% block main %}
        <div class="contentQuiz">
            <div class="quizHeader">

                <!---------------------------BOUTON HOME------------------------------->
                <div class="homeButtonQuiz">
                    <a href="{{ path('home_lesZanimeo') }}"><img src="{{ asset('assets/img/main/home2.jpg') }}" alt="Retour à l'accueil"></a>
                </div>

                <!---------------------------BOUTON QUIZ------------------------------->
                <div class="quiz2Button">
                    <img src="{{ asset('assets/img/main/quiz2.png') }}" alt="">
                </div>
            </div>

            <div class="content1Quiz">
                <div class="contentLeftQuiz">
                    <img class="imgQuizTop" src="{{ asset('assets/img/animals/farm.png') }}" alt="">
                    <img class="imgQuizEnd" src="{{ asset('assets/img/animals/bugs.png') }}" alt="">
                    <img class="imgQuizTop" src="{{ asset('assets/img/animals/birds.png') }}" alt="">
                </div>

                <div class="contentRightQuiz">
                    {%  if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                        <h1>Bienvenue {{ app.user.username }}, teste tes connaissances !</h1><br><br>
                    {% else %}
                        <h1>Bienvenue, teste tes connaissances !</h1><br><br>
                    {% endif %}
                    <p>18 questions sur tes animaux préférés.<br><br>Lance-toi pour savoir si tu as bien tout retenu !</p><br><br>
                    <div class="btn-group" role="group" aria-label="Button">
                        <a href="{{ path('questions', {'id': 1, 'goodResponses': 0}) }}"><button type="button" class="btn btn-info">Lancer le Quiz</button></a>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/responses.html.twig
{% extends 'base/baseQuiz.html.twig' %}

{% block main %}
    <main>
        <div class="contentQuiz">
            <div class="quizHeader">
                <div class="homeButtonQuiz">
                    <a href="{{ path('home_lesZanimeo') }}"><img src="{{ asset('assets/img/main/home2.jpg') }}" alt=""></a>
                </div>
                <h1 class="questionNumber">{{ responses.libelle }}</h1>
            </div>

            <div class="contentQuestionsQuiz">

                <!---------------------------IMAGE ANIMAL------------------------------->
                <div class="contentImgQuiz">
                    <img src="{{ asset('assets/img/animals') }}/{{ responses.image }}" alt="">
                </div>

                <!---------------------------CONTENU REPONSES------------------------------->
                <div class="contentTextQuiz">

                        <!---------------------------CONDITION SCORE------------------------------->
                        {% if responses.id >= 35 %}
                            {% if responses.message == 'BRAVO, BONNE REPONSE !' %}
                                <h1 class="bravoResponse">{{ responses.message }}</h1><br><br>
                                <p>{{ responses.resume }}</p><br><br>
                                <a href="{{ path('score', {'id': responses.questions.id+1, 'goodResponses': goodResponses +1 }) }}"><button type="button" class="btn btn-info">Obtiens ton score !</button></a>
                            {% else %}
                                <h1 class="desoleResponse">{{ responses.message }}</h1><br><br>
                                <p>{{ responses.resume }}</p><br><br>
                                <a href="{{ path('score', { 'goodResponses': goodResponses }) }}"><button type="button" class="btn btn-info">Obtiens ton score !</button></a>
                            {% endif %}
                        {% elseif responses.message == 'BRAVO, BONNE REPONSE !' %}
                            <h1 class="bravoResponse">{{ responses.message }}</h1><br><br>
                            <p>{{ responses.resume }}</p><br><br>
                            <a href="{{ path('questions', {'id': responses.questions.id+1, 'goodResponses': goodResponses +1 }) }}"><button type="button" class="btn btn-info">Continuer</button></a>
                        {% else %}
                            <h1 class="desoleResponse">{{ responses.message }}</h1><br><br>
                            <p>{{ responses.resume }}</p><br><br>
                            <a href="{{ path('questions', {'id': responses.questions.id+1, 'goodResponses': goodResponses }) }}"><button type="button" class="btn btn-info">Continuer</button></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}